image: "golang:{{cookiecutter.docker_build_image_version}}"

.go_setup: &go_setup
  variables: &go_variables
    GOFLAGS: "-mod=readonly"
    GOMODCACHE: "$CI_PROJECT_DIR/.go/pkg/mod"
  cache:
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p .go/pkg/mod

.only_production: &only_production
  refs:
    - master
    - main

stages:
  - test

unit-test:
  <<: *go_setup
  stage: test
  variables:
    <<: *go_variables
  script:
    - make test
    - go tool gocover-cobertura < cover.out > cover.xml
  coverage: '/total:\s*\(statements\)\s*\d+.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cover.xml

lint:
  <<: *go_setup
  stage: test
  variables:
    <<: *go_variables
  script:
    - make lint

benchmark:
  <<: *go_setup
  stage: test
  variables:
    <<: *go_variables
  script:
    - make bench
