services:
  db:
    image: postgres:17-alpine
    restart: always
    profiles: ["deps"]
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "{{cookiecutter.app_name}}_dev"
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis:8-alpine
    restart: always
    profiles: ["deps"]
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    profiles: ["deps"]
    ports:
      - "8088:8080"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    profiles: ["obs"]
    ports:
      - "9100:9090"
    volumes:
      - ./deploy/local/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: always
    profiles: ["obs"]
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./deploy/local/grafana/provisioning:/etc/grafana/provisioning
      - ./deploy/local/grafana/dashboards:/var/lib/grafana/dashboards

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    profiles: ["obs"]
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
