# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" , "master"]

jobs:
  build:
    concurrency:
      group: {% raw -%}ci-${{ github.job }}-${{ github.ref }}{%- endraw %}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "{{cookiecutter.docker_build_image_version}}"
        cache: true
    - name: Build
      run: make build

  test:
    concurrency:
      group: {% raw -%}ci-${{ github.job }}-${{ github.ref }}{%- endraw %}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "{{cookiecutter.docker_build_image_version}}"
        cache: true
    - name: Test
      run: make test
    - name: Generate coverage report
      run: go tool gocover-cobertura < cover.out > cover.xml
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: cover.xml

  benchmark:
    concurrency:
      group: {% raw -%}ci-${{ github.job }}-${{ github.ref }}{%- endraw %}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "{{cookiecutter.docker_build_image_version}}"
        cache: true
    - name: Benchmark
      run: make bench

  lint:
    concurrency:
      group: {% raw -%}ci-${{ github.job }}-${{ github.ref }}{%- endraw %}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "{{cookiecutter.docker_build_image_version}}"
        cache: true
    - name: Vulnerability Check
      run: make vulncheck
    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.8
        args: --timeout 5m
